name: Generate GitHub Contribution Snake Game

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Snake Game SVG
        uses: Platane/snk@master  # Ensure you're using the correct version
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: ./github-contribution-snake.svg  # Adjust path if necessary

      - name: Upload SVG to Branch
        uses: EndBug/add-and-commit@v7
        with:
          path: github-contribution-snake.svg
          message: 'Update GitHub contribution snake game'
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          push: true
