name: Generate GitHub Snake

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate snake animation
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: 'dist/github-contribution-snake.svg'

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          add: 'dist/github-contribution-snake.svg'
          message: 'Update GitHub contribution snake game'
          author_name: GitHub Actions
          author_email: actions@github.com
          push: true
